export class Enquiry {
  constructor(
    // This is optional because it's generated by the backend
    public studentName: string,
    public studentPhno: string,
    public courseName: string,
    public classMode: string,
    public enqStatus: string,
    public createdDate?: string, // These fields are optional, as,they will be set by the backend
    public updatedDate?: string,
    public counsellorId?: number, // This will link the enquiry to a counsellor
    public eId?: number
  ) {}
}
